### ISSUE TITLE
Not detecting any smoke

### ISSUE THREAD

**Issue by mudasarK** [JoHyukJun/tensorflow-lite-raspberrypi-object-detection#1]
Hi, I run your code, couldn't get any smoking detection in it, do you have a working demo?

**Comment by psmng** [comment]
There was a case that the deep learning model didn't work properly. The reason is that cigarettes are too small in their image. I could sort of solve it by cropping the whole person from the image.

If you just want to check the deep learning model, I recommend that you first check smoking close to the camera.

And you can get the details. However, be aware that it is written in Korean.

detailed info - http://bushitechnology.com/work/raspberry-pi-lab

Thank you.
